services:
  nuxt:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NUXT_HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true  # Для отслеживания изменений файлов
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: